services:
  web:
    build: App
    ports:
      - "80:80"
    networks:
      - default
    links:
      - db:database
  db:
    build: Database
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - default
      